### ISSUE TITLE
Loading Character Slot Causes Wrong Genemods

### ISSUE THREAD

**Issue by Aliannera** [HearthOfHestia/Nebula#101]
#### Description of issue

When loading up the character slot, it instead loaded what seems to be the top most genemod (in this case, bee antenna and hide species-sprite tail). Did not happen when quitting and reconnecting, only when loading the character slot. It also does not happen if you have no genemod set (aka Normal).

#### Difference between expected and actual behavior

Try to save cat ears, instead load bee antenna.

#### Steps to reproduce

Set genemod to anything but Normal, save and try to load.

Edit: On a new round, it had the same issue, character data had the wrong genemods.

#### Specific information for locating

N/A

#### Length of time in which bug has been known to occur

N/A

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: Revision Unknown
Game ID: cej-duaC

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MarinaGryphon** [comment]
Fixed.
