### ISSUE TITLE
Some ladders are blocked by the tiles they're on

### ISSUE THREAD

**Issue by Kaksisilma** [HearthOfHestia/Nebula#106]
#### Description of issue

![power](https://user-images.githubusercontent.com/54181477/135766517-d56e5c96-9920-4cfb-8d5a-0fc45c2ca4b1.PNG)

#### Difference between expected and actual behavior

The floor should not be blocking the ladder from heading down. (This one, especifically, connects the Second deck starboard quarter to the first deck.)

#### Steps to reproduce

find ladder
try to go up
cry

#### Length of time in which bug has been known to occur

Since the test on 10/3/2021

#### Client version, Server revision & Game ID

Server Revision: Revision Unknown
Game ID: cek-cx0b
Current map: ISEO Endeavour

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Mapping issue, plated catwalks block ladders by design. Pretty sure the unplated type does not.
