### ISSUE TITLE
Engineering Shard cannot pull things.

### ISSUE THREAD

**Issue by chaoko99** [HearthOfHestia/Nebula#109]
#### Description of issue
Engineer shards cannot pull canisters, thus blocking them from setting the engine.

#### Difference between expected and actual behavior
To be able to set up the engine on lowpop without making a dedicated character for the task.

#### Steps to reproduce
ctrl click a canister. Nothing happens.

#### Specific information for locating

engineering shard

#### Length of time in which bug has been known to occur

Probably since grab refactor.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: Revision Unknown
Game ID: cek-dBO9
Current map: ISEO Endeavour

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Mazianni** [comment]
issue is incorrect - drones/borgs can not grab period.

**Comment by lolman360** [comment]
resolved by #134
