### ISSUE TITLE
Engineering borgs cannot interact iwth the pipe fabricator. Neither can drones.

### ISSUE THREAD

**Issue by chaoko99** [HearthOfHestia/Nebula#110]
#### Description of issue
See title. Cannot open the interface.

#### Difference between expected and actual behavior
To be able to do this.

#### Steps to reproduce
Click on pipe printer. Nothing.

#### Specific information for locating

AI shard, borg, etc. Drones.
11

#### Length of time in which bug has been known to occur

Not a clue.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: Revision Unknown
Game ID: cek-dBO9
Current map: ISEO Endeavour

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Did you wrench it down? Can't reproduce this upstream on dev.
![image](https://user-images.githubusercontent.com/2468979/135781281-f70a2a90-58ec-45fc-a310-0fdb8fa0415e.png)

**Comment by Kaksisilma** [comment]
The pipe dispenser starts unwrenched and no one is able to interact with it.
Once you wrench it down, it works normally, even for shells/AIs/drones

![sippy](https://user-images.githubusercontent.com/54181477/139542692-f0805b36-938c-4d68-b033-7fb9462878a1.png)

Client Version: 513
Server Revision: a3ced1386856aea66c7f106ddfa8b5cf021c6802 - Ahoy,-CMO.-I've-overdosed-on-fentanyl-and-now-I'm-going-to-die - 2021-10-30
Game ID: ceL-cKlF
Current map: ISEO Endeavour
