### ISSUE TITLE
Silicon lights are basically unusable.

### ISSUE THREAD

**Issue by chaoko99** [HearthOfHestia/Nebula#113]
#### Description of issue
AI Shells and drone flashlights are so dim as to be almost completely unusable.

#### Difference between expected and actual behavior
To be able to see. 

Instead I get like a penlight tier illumination.
#### Steps to reproduce
Activate lights from the silicon tab.
Enjoy the passive luminescence of a piece of quartz at about 3 photons an hour.

#### Specific information for locating

AI shells, drones.

#### Length of time in which bug has been known to occur

Likely since O7 Lights

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: Revision Unknown
Game ID: cek-dBO9
Current map: ISEO Endeavour

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HearthOfHestia/Nebula/issues)

**Comment by MistakeNot4892** [comment]
![image](https://user-images.githubusercontent.com/2468979/135781415-181b1e87-2d09-4e3e-b6ec-03b269494c6b.png)
Can't reproduce on Neb dev.
