### ISSUE TITLE
Diluted cleaner doesn't work in a mop

### ISSUE THREAD

**Issue by Tristan63** [HearthOfHestia/Nebula#115]
#### Description of issue
When cleaning with janitors mop, it will say "You've finished mopping!" with a wet mop that has space cleaner but not actually clean anything.

#### Difference between expected and actual behavior
Should clean when you finish mopping, but isn't.

#### Steps to reproduce
1. Fill janicart with water and space cleaner mix
2. Wet mop
3. Clean something that you should be able to clean
4. Observe as you get cucked into using soap
#### Specific information for locating

Janicart, mop, space cleaner, soap

#### Length of time in which bug has been known to occur

unknown, just noticed it

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: Revision Unknown
Game ID: cek-dBO9
Current map: ISEO Endeavour

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HearthOfHestia/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Believe this was fixed by Jade?

**Comment by MarinaGryphon** [comment]
Indeed, now it uses get_dirtiness on reagent holders.
