### ISSUE TITLE
Omni gas filter don't connect with connector ports on roundstart

### ISSUE THREAD

**Issue by quardbreak** [HearthOfHestia/Nebula#13]
#### Description of issue

![изображение](https://user-images.githubusercontent.com/44920739/125175358-34cb7f00-e1d4-11eb-82dc-7b8f16ec9f1c.png)

#### Difference between expected and actual behavior

Connected by default

#### Steps to reproduce

Startup game

#### Specific information for locating

X 54, Y 94, Z 3

#### Length of time in which bug has been known to occur

Found today

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 265cac4eee019279b10aa269c5e568d9a9a61f4f - dev - 2021-07-10
Game ID: ccX-dbs2
Current map: ISEO Endeavour

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HearthOfHestia/Nebula/issues)

**Comment by Mazianni** [comment]
This filter no longer exists.
