### ISSUE TITLE
You can access to AI room from above, ignoring turrets

### ISSUE THREAD

**Issue by quardbreak** [HearthOfHestia/Nebula#14]
#### Description of issue

This is mostly design problem. If you have rouge AI it would be very easy to defeat him by just removing floor above and throwing EMP.

#### Difference between expected and actual behavior

Recommended to move AI room to top ship zlevel.

#### Specific information for locating

X 127, 103, 1 and above

#### Length of time in which bug has been known to occur

Today

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HearthOfHestia/Nebula/issues)

**Comment by Mazianni** [comment]
Nebula doesn't have floors that prevent removal. Unfortunate.

**Comment by Mazianni** [comment]
Citing above comment, this is a wont-fix until upstream changes this.
