### ISSUE TITLE
Overlays are not applied properly.

### ISSUE THREAD

**Issue by Kaksisilma** [HearthOfHestia/Nebula#140]
#### Description of issue

When you receive a lot of brute damage, a red overlay forms around your screen. Similarly, receiving too much oxygen damage causes your screen to become blacker, and putting on a welding helmet significantly obscures your vision.

Those are all what I am calling 'overlays'. They are not being applied at all in game. The oxygen damage overlay does not work, nor does the red, brute damage overlay. And putting on a welding helmet does not change your vision.

All of those overlays are available at 'icons/mob/screen_full.dmi'

#### Difference between expected and actual behavior

Overlays should be properly applied when the conditions are met.

#### Steps to reproduce

Deal yourself a lot of oxygen or brute damage, or wear a welding helmet.
There will be no distortions on your screen view.

#### Specific information for locating

icons/mob/screen_full.dmi (Where the overlays are stored)
code\_onclick\hud\fullscreen.dm (Where some of the overlay code is stored.)
code\modules\mob\living\carbon\human\life.dm - Line 671 (One of the mentions of the fire and brute damage overlay.)

#### Length of time in which bug has been known to occur

Since an unrelated test in a private server today, 10-30-2021.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 4a399c669ace3313da76725e724cd818650e8865 - Ahoy,-CMO.-I've-overdosed-on-fentanyl-and-now-I'm-going-to-die - 2021-10-30
Game ID: ceL-cyt8
Current map: ISEO Endeavour

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HearthOfHestia/Nebula/issues)

**Comment by Kaksisilma** [comment]
Issue was reproduced upstream.

**Comment by MarinaGryphon** [comment]
This is not a bug, this is a config option, iirc.

**Comment by MarinaGryphon** [comment]
Okay, no, only the welder one is.
