### ISSUE TITLE
Autolathe issue

### ISSUE THREAD

**Issue by TheDeadlyPanda1** [HearthOfHestia/Nebula#148]
#### Description of issue
I can not print anything from auto-lathes. I could not print anything from the surgery printers last time I used them but i am not sure if they are still bugged. When I try to use the Auto-lathes it has the top half, the materials counter, the current build and pending thing, then it has category and filter. Then there is the design cost and options bar but that is the end of the page and no options to print anything.

#### Difference between expected and actual behavior
Option to print something. No options to print anything. 

#### Steps to reproduce
Just opening the UI for the system is how it works for me.

#### Specific information for locating

I don't know.

#### Length of time in which bug has been known to occur

I do not know, but It has occurred every time I have tried to use it.

#### Client version, Server revision & Game ID

514.1569, 514.1568, ceM-cbnt>

#### Issue bingo

- [ Issue could be reproduced at least once
-  Issue could be reproduced by different players
-  Issue could be reproduced in multiple rounds
-  Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HearthOfHestia/Nebula/issues)

**Comment by MistakeNot4892** [comment]
This should be fixed as of the base tech level changes on Neb last week.

**Comment by MarinaGryphon** [comment]
Please open a new issue if this still happens.
