### ISSUE TITLE
Sharks missing dead sprite

### ISSUE THREAD

**Issue by J-A-R-J-A-R** [HearthOfHestia/Nebula#152]
#### Description of issue
Sharks have a dead sprite right? Well if they dont they should. I think they do though and its just not being called

![aaaaaaaa](https://user-images.githubusercontent.com/81835687/139604583-a5aaf41c-0f90-41d4-adc5-012ae147b472.PNG)

#### Difference between expected and actual behavior
Cosmoshark should look dead
it look very alive

#### Steps to reproduce

Kill a cosmoshark
Watch as you click more not realizing its dead

#### Specific information for locating

Cosmoshark

#### Length of time in which bug has been known to occur

Today

#### Client version, Server revision & Game ID

Game ID: ceM-diF5>
Client BYOND Version: 514.1568
Server BYOND Version: 514.1568
Current map: ISEO Endeavour
TGS version: 4.14.3
DMAPI version: 5.3.0

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HearthOfHestia/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Cosmoshark does have a dead icon but for whatever reason it also completely overrides `/mob/living/simple_animal/hostile/carp/shark/on_update_icon` to be a noop.

**Comment by hermaplusplus** [comment]
Appears fixed by NebulaSS13/Nebula#2248
