### ISSUE TITLE
Switching Characters from one that doesn't have body types fucks up pronouns and bodytype

### ISSUE THREAD

**Issue by PigeonLord** [HearthOfHestia/Nebula#158]
#### Description of issue
This is a bit of a weird one. Basically, if you from a character that has no bodytypes (like an Utility Frame) to one, the gender options reset to default.
Simply reloading the slot fixes it, but it shouldn't happen in the first place

#### Difference between expected and actual behavior
I would expect that loading slot would also load bodytype and pronouns correctly.

#### Steps to reproduce
1)Select a character that has both bodytypes
![1](https://user-images.githubusercontent.com/36793141/140606857-a45c5818-b239-410f-b72c-5f030191d7d6.png)
2)Switch to a character that has no bodytypes
![2](https://user-images.githubusercontent.com/36793141/140606900-7eb670a9-4117-4f20-a589-e1f2c7130538.png)
3)Switch back to the first character, who now has switched both pronouns and bodytype
![bodytype](https://user-images.githubusercontent.com/36793141/140606954-6e9b925f-249f-4593-ace8-764d840ab030.png)

#### Specific information for locating
Bodytype, Pronouns, Utility Frame

#### Length of time in which bug has been known to occur
Unknown

#### Client version, Server revision & Game ID
Game ID: ceS-bxHN>
Client BYOND Version: 514.1568
Server BYOND Version: 514.1569
Current map: ISEO Endeavour
TGS version: 4.15.7
DMAPI version: 5.3.0

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
This has been reported on Neb as well, appears to be related to sanitization being applied using the previous species. Workaround on Neb was to load the slot twice since that skips the weird sanitization.
