### ISSUE TITLE
Canned Drinks Display Improper Description

### ISSUE THREAD

**Issue by Rowtree** [HearthOfHestia/Nebula#160]
#### Description of issue
Canned drinks have their own specific description, but instead, the can displays the descriptive text for whatever drink is inside it.
For example:
In the code, the iced tea is supposed to have "desc = "That sweet, refreshing southern earthy flavor. That's where it's from, right? South Earth?"", however in practice it displays "desc = "That sweet, refreshing southern earthy flavor. That's where it's from, right? South Earth?""

#### Difference between expected and actual behavior
See above. Should display proper desc

#### Steps to reproduce
Take a look at any can in-game.

#### Length of time in which bug has been known to occur
Unknown

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HearthOfHestia/Nebula/issues)

**Comment by MistakeNot4892** [comment]
You've listed the same description twice.
This was an intentional change on Neb (`/obj/item/chems/drinks/on_reagent_change`) so that glasses would update their strings appropriately, but should probably be overridden for sealed drinks.

**Comment by hermaplusplus** [comment]
Appears fixed by NebulaSS13/Nebula#2248
