### ISSUE TITLE
If you Remove a Pen from your clipboard while both of your hands are occupied, it will vanish 

### ISSUE THREAD

**Issue by PigeonLord** [HearthOfHestia/Nebula#167]
#### Description of issue
If you press the "Remove Pen" button on the Clipboard while both of your hands are occupied, the Pen will disappear.

#### Difference between expected and actual behavior
I expect the button to not work at all, or at least drop the pen to the ground rather than in the Twilight Zone.

#### Steps to reproduce
1)Put Pen in clipboard
2)Put whatever in empty hand
3)Click Remove Pen button
4)Watch in amazement as Pen reenacts Houdini

#### Specific information for locating

Clipboard, Pen, Remove Pen

#### Length of time in which bug has been known to occur

Unknown

#### Client version, Server revision & Game ID

Game ID: ceZ-dbrv>
Client BYOND Version: 514.1568
Server BYOND Version: 514.1569
Current map: ISEO Endeavour
TGS version: 4.15.7
DMAPI version: 5.3.0

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Code as written uses put_in_hands and should end up with it on the floor under you.
