### ISSUE TITLE
Chair sprite overlay bug

### ISSUE THREAD

**Issue by Kaksisilma** [HearthOfHestia/Nebula#171]
#### Description of issue

![fomg](https://user-images.githubusercontent.com/54181477/141663181-2eb06789-938e-4083-8d3e-c5d23b4aca57.PNG)
I am buckled to this chair facing north, yet I can not see the sprite of the chair's rest.

#### Difference between expected and actual behavior

We should be able to see the chair's rest overlayed on top of our sprite.

#### Steps to reproduce

 - Find chair
 - Rotate it to north
 - buckle
 - you are sitting very awkardly on top of it

#### Length of time in which bug has been known to occur

For a few tests now. Last experienced on 21:38

#### Client version, Server revision & Game ID

Game ID: ce1-aaKJ>
Client BYOND Version: 513.1536
Server BYOND Version: 514.1569
Current map: ISEO Endeavour
TGS version: 4.15.7
DMAPI version: 5.3.0

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HearthOfHestia/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Likely a Neb bug related to the layer/plane offset rewrites.
