### ISSUE TITLE
Some cameras start de-activated.

### ISSUE THREAD

**Issue by Kaksisilma** [HearthOfHestia/Nebula#172]
#### Description of issue

Some cameras seem to start de-activated. 

#### Difference between expected and actual behavior

No cameras should start de-activated.

#### Steps to reproduce

 - join server
 - open camera monitoring
 - no

#### Specific information for locating
Here's a screenshot of all the missing cameras in the camera monitoring program.

![1](https://user-images.githubusercontent.com/54181477/141663274-411dcac7-1c76-4972-a854-09c3f9f44985.PNG)

![2](https://user-images.githubusercontent.com/54181477/141663275-e7a45c82-b7e3-498e-812e-f9b8bc6e04b6.PNG)

![3](https://user-images.githubusercontent.com/54181477/141663277-3be5f3be-2947-475e-b7eb-10e98246d708.PNG)

![4](https://user-images.githubusercontent.com/54181477/141663284-458609e5-8d81-4d29-b3c0-7fd3534abc53.PNG)

![5](https://user-images.githubusercontent.com/54181477/141663286-d2924000-343d-4b76-84d5-4da2caba9866.PNG)

![6](https://user-images.githubusercontent.com/54181477/141663288-b1d026cc-360a-4982-ba8a-bdc7684a461d.PNG)

![7](https://user-images.githubusercontent.com/54181477/141663290-a7334ec6-dd63-45d4-a961-8265ec8857a8.PNG)

#### Length of time in which bug has been known to occur

Observed first a few weeks ago and again today.

#### Client version, Server revision & Game ID

Game ID: ce1-aaKJ>
Client BYOND Version: 513.1536
Server BYOND Version: 514.1569
Current map: ISEO Endeavour
TGS version: 4.15.7
DMAPI version: 5.3.0

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HearthOfHestia/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Does Hearth have the network camera changes? Jade mentioned Torch network coverage might be fucky so it could be related to that.
