### ISSUE TITLE
You can't get pick up the deck of cards at all

### ISSUE THREAD

**Issue by PigeonLord** [HearthOfHestia/Nebula#178]
#### Description of issue
You can't pick up the deck of cards at at all, clicking on it just draws a card, even using the "Pick up" command from the right click menu just gives you a card

#### Difference between expected and actual behavior
I expect to be able to get the deck

#### Steps to reproduce
1)Spawn with a deck of cards from your loadout or buy it from a vending machine
2)Try to put it in your hand

#### Specific information for locating

deck of cards

#### Length of time in which bug has been known to occur

unknown

#### Client version, Server revision & Game ID

Game ID: ce1-cUVC>
Client BYOND Version: 514.1568
Server BYOND Version: 514.1569
Current map: ISEO Endeavour
TGS version: 4.15.7
DMAPI version: 5.3.0

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MarinaGryphon** [comment]
Drag it to yourself.
This is still an issue when it's in a bag, though.

**Comment by PigeonLord** [comment]
> Drag it to yourself. This is still an issue when it's in a bag, though.

Nope, it doesn't work when it's outside a bag either.
