### ISSUE TITLE
No underwear wardrobe in crew areas

### ISSUE THREAD

**Issue by Rowtree** [HearthOfHestia/Nebula#27]
#### Description of issue
There are no wardrobes that let you spawn undershirts and underwear in public areas like dorms. There are currently only two underwear wardrobes, one in the vacant dorms (in maints), and one in the CO's office.

#### Difference between expected and actual behavior
N/A

#### Steps to reproduce
N/A

#### Specific information for locating
N/A

#### Length of time in which bug has been known to occur
N/A

#### Client version, Server revision & Game ID
N/A

#### Issue bingo
N/A

**Comment by Mazianni** [comment]
Closed #36
