### ISSUE TITLE
SM produces Phoron, yet it is not a recognizeable gas to be filtered

### ISSUE THREAD

**Issue by Kaksisilma** [HearthOfHestia/Nebula#32]
#### Description of issue

Might be intended behavior. SM produces Phoron gas, but you are unable to manipulate it through filters.

#### Difference between expected and actual behavior

I'm actually not sure if Phoron was even meant to exist here, yet it does and is a by-product of the SM reaction

![froge](https://user-images.githubusercontent.com/54181477/129460637-33e6950e-8d34-4bc7-a2d9-db96db256b23.png)

![Capture2](https://user-images.githubusercontent.com/54181477/129460641-c38e3f3f-a93e-4cbd-9e3b-f8c2a88439fc.PNG)

#### Steps to reproduce

Turn on SM on a hydrogen setup
Watch as the PH % rises.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: Revision Unknown
Game ID: cdw-dlFQ

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HearthOfHestia/Nebula/issues)

**Comment by Mazianni** [comment]
Not phoron  - labeling in SM monitoring has not been updated to reflect exotic matter. 

Filtering will be fixed once https://github.com/NebulaSS13/Nebula/pull/1874 is merged.

**Comment by MarinaGryphon** [comment]
Fixed in #25.
