### ISSUE TITLE
RUST airlock does not work.

### ISSUE THREAD

**Issue by Kaksisilma** [HearthOfHestia/Nebula#42]
#### Description of issue

'Airlock' used to enter the R-UST will not asnwer to the controller.

#### Difference between expected and actual behavior

It should answer to the controller on the wall.

#### Steps to reproduce

Try to go inside rust chamber

Press 'Cycle to Interior' on the controller

no

#### Length of time in which bug has been known to occur

Since the test at 08/09/2021

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: Revision Unknown
Game ID: cdV-dqRP
Current map: ISEO Endeavour

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by lolman360** [comment]
Issue still occurs as of 17/10/2021

**Client version, Server revision & Game ID**

Client Version: 513.1536
Server Revision: Revision Unknown
Game ID: cex-dG9V
Current map: ISEO Endeavour
