### ISSUE TITLE
Double windows pop up when you hit F4 for mes

### ISSUE THREAD

**Issue by DeadmonWonderland** [HearthOfHestia/Nebula#61]
#### Description of issue

Using F4 to open the box to type me's into opens two boxes.
https://i.gyazo.com/9a0c8fcc5cd1b9b822c826ae1e7d01a0.mp4

#### Difference between expected and actual behavior

Only one box should open.

#### Steps to reproduce

Hit F4.

#### Specific information for locating

Not sure on this one.

#### Length of time in which bug has been known to occur

A while?

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: Revision Unknown
Game ID: cd6-dERp

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Apparently fixed by https://github.com/NebulaSS13/Nebula/pull/2134
