### ISSUE TITLE
PDAs have some wierd shading or something on them

### ISSUE THREAD

**Issue by DeadmonWonderland** [HearthOfHestia/Nebula#64]
#### Description of issue

https://i.gyazo.com/60dddfc6d0fe04464f47e727a2241a7e.png

#### Difference between expected and actual behavior

PDA's shouldn't look like they just got spray painted blue.

#### Steps to reproduce

Spawn in and look at your PDA.

#### Specific information for locating

No clue on this one.

#### Length of time in which bug has been known to occur

No idea.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: Revision Unknown
Game ID: cd6-dERp

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HearthOfHestia/Nebula/issues)

**Comment by Mazianni** [comment]
Command PDAs are a temp and on the to-do to replace.
