### ISSUE TITLE
Underwear (Shirts, Socks, and Pants) disappear whenever wearing something over them.

### ISSUE THREAD

**Issue by Rowtree** [HearthOfHestia/Nebula#65]
#### Description of issue
Wearing underwear, and then putting clothes on above them makes them disappear. They reappear if you take them off and put them back on, but will vanish again once your icon updates (i.e. picking something up)

#### Difference between expected and actual behavior
pants should not be invisible

#### Steps to reproduce
wear pants, put clothes on

#### Specific information for locating
N/a

#### Length of time in which bug has been known to occur
N/a

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HearthOfHestia/Nebula/issues)

**Comment by MistakeNot4892** [comment]
Fixed upstream: https://github.com/NebulaSS13/Nebula/pull/2109
