### ISSUE TITLE
Walking through various objects and an inability to go down stairs automatically.

### ISSUE THREAD

**Issue by DeadmonWonderland** [HearthOfHestia/Nebula#74]
#### Description of issue

Racks and these tank things can be walked through, see https://i.gyazo.com/20ec80ca620c00594ef9683c310160f8.mp4

Also you can't go down stairs without using the move down verb.

#### Difference between expected and actual behavior

The people on the ship aren't ghosts (I think) they should be stopped by solid objects and not be able to levitate above stairs.

#### Steps to reproduce

Walk into a rack, walk through it. Walk down stairs, float.

#### Length of time in which bug has been known to occur

Not sure.

#### Client version, Server revision & Game ID

Private server running client 514.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HearthOfHestia/Nebula/issues)

**Comment by MarinaGryphon** [comment]
Was there gravity?
Also, for future reference, please have just one bug per issue report.
