### ISSUE TITLE
Poorly-mapped Thruster areas.

### ISSUE THREAD

**Issue by Kaksisilma** [HearthOfHestia/Nebula#86]
#### Description of issue

![fwomg](https://user-images.githubusercontent.com/54181477/134819558-9ce33bd9-10d1-4fb1-86bd-4efc51cafe29.PNG)
#### Difference between expected and actual behavior

This prevents the engine from turning on.

#### Steps to reproduce

Run up to bridge
turn all thrusters on
no

#### Length of time in which bug has been known to occur

Since test on 9/26/2021

#### Client version, Server revision & Game ID

Server Revision: Revision Unknown
Game ID: ced-cNpl
Current map: ISEO Endeavour

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HearthOfHestia/Nebula/issues)

**Comment by Mazianni** [comment]
resolved
